#!/usr/bin/python3

print("give me a bottle of rum!")

Lorem Ipsum
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a nunc id lacus mollis mattis sit amet vitae lorem. Praesent sagittis velit at magna consequat vehicula. Vestibulum tempor ac lectus sed commodo. Ut dui nibh, laoreet quis tempor vel, posuere et orci. Nullam velit elit, vehicula id ex eget, scelerisque dapibus sem. Aenean quis eros eu enim laoreet ultrices ut sed tortor. Donec quis velit imperdiet, congue magna eget, tincidunt tortor. Nullam convallis nisi sem, sed accumsan erat pulvinar vel. Sed ultrices aliquam purus, ut vulputate dui faucibus nec. Aenean imperdiet justo vitae ullamcorper sodales. In hac habitasse platea dictumst. Nullam ut velit dui.

Donec in velit sed odio efficitur dapibus. Aenean at congue turpis, sit amet iaculis arcu. Integer accumsan diam vehicula tortor gravida, sed pretium velit rutrum. Mauris est eros, lobortis ut egestas vel, tincidunt eu nibh. Aenean id sodales mi. Praesent varius urna eget mi pulvinar egestas. Morbi quam quam, accumsan ac tincidunt sed, imperdiet vitae ante. Proin vitae semper dui. Phasellus rhoncus eget orci venenatis sagittis. Proin lacinia ante at nisi varius rutrum. Integer sollicitudin tempus ipsum.

Phasellus porttitor bibendum aliquam. Phasellus nec augue consectetur, venenatis ante ut, accumsan sapien. Donec vel egestas felis, in porttitor leo. Morbi ultricies at felis at porta. Aliquam sed finibus diam, ut posuere erat. In hac habitasse platea dictumst. Sed diam libero, congue vel pulvinar quis, bibendum quis nibh.

Morbi tempus viverra mi at pharetra. Duis sollicitudin efficitur lorem non pellentesque. Ut lacus massa, imperdiet et commodo non, iaculis ut lorem. Maecenas metus diam, feugiat a molestie non, gravida id erat. Vivamus hendrerit condimentum laoreet. Nulla in turpis luctus, convallis mauris vel, molestie magna. Vivamus vitae finibus purus. Aliquam condimentum nibh et risus vestibulum, ac pulvinar est egestas. Duis a rhoncus orci, vel porttitor mi. Pellentesque sit amet elementum ipsum, sit amet laoreet arcu.

Aenean nisi dui, ultrices vel semper hendrerit, faucibus et purus. Vivamus et lorem risus. Curabitur vitae justo dignissim, laoreet eros ac, accumsan purus. Ut elementum sapien in magna hendrerit, a posuere mi auctor. Maecenas consequat auctor elit sit amet gravida. Cras eget mauris eget risus sollicitudin venenatis eget id ipsum. Donec laoreet metus mi, sit amet molestie magna maximus sit amet. Fusce mollis mollis risus, id tempus justo feugiat quis. Vivamus suscipit nibh nulla, at dictum dolor sodales sit amet. Integer vel malesuada ante, eget imperdiet sem. Duis porta magna et diam efficitur maximus. Ut molestie ac nisi eget condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer vitae sagittis urna, non viverra velit. Donec consectetur ante sapien, eu molestie tellus ultrices vitae.

Fusce rutrum posuere egestas. Integer non velit mi. Aenean efficitur porta erat, ut vestibulum diam ultricies et. Curabitur efficitur erat eu ipsum finibus, eget tincidunt nunc semper. Donec efficitur dui ac commodo venenatis. Morbi ex augue, commodo in ex non, euismod laoreet orci. Morbi sodales lacus mauris, non hendrerit risus interdum non. Donec sit amet massa lacinia, venenatis ante eget, vehicula tellus. Maecenas non arcu a est convallis porttitor sed quis risus. Ut risus orci, fringilla nec tincidunt eu, vestibulum ultricies tortor. Vestibulum finibus leo a elit varius tincidunt id ac felis. Donec commodo consequat porttitor. Curabitur pretium mi ante, nec accumsan erat feugiat id. Vivamus commodo sapien sit amet lorem sagittis, eget venenatis mauris congue. Nullam accumsan nunc ut odio pharetra, sed fermentum magna consectetur. Integer est justo, euismod vel interdum sit amet, suscipit ac eros.

Fusce ultricies eros quis arcu pellentesque, sit amet consequat tortor condimentum. Vivamus sed sodales metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer mattis nulla vitae ante dapibus vestibulum. Cras facilisis ultricies odio, vel efficitur massa placerat et. Sed sodales neque vitae tincidunt iaculis. Nam finibus leo laoreet purus interdum, a viverra tortor sollicitudin. Aenean vehicula aliquam tortor nec euismod. Fusce ultrices tincidunt vestibulum. Vivamus rutrum, odio vitae luctus egestas, mauris magna lobortis felis, ut semper ante sem vel augue. Sed placerat metus ut risus tincidunt, ut placerat mi lobortis. Proin egestas egestas consequat. Suspendisse et dolor ut quam vulputate facilisis.

Nullam pretium commodo augue efficitur vehicula. Donec vitae elit eu nunc varius aliquam. Morbi malesuada interdum nunc in elementum. Vivamus mattis, elit eu placerat finibus, libero massa pharetra dui, at viverra nisl quam sed quam. Suspendisse at felis cursus, tristique erat quis, tincidunt lectus. Ut gravida diam quis tortor iaculis, quis eleifend odio efficitur. Nunc varius, diam sit amet maximus ultrices, nulla mauris pellentesque felis, nec blandit tellus ex sit amet nibh. Donec ac libero lorem. Mauris bibendum velit sit amet leo fringilla, id elementum urna auctor. Morbi id ex sem. Vivamus pellentesque velit vel quam fringilla, nec mattis turpis scelerisque.

Sed suscipit sapien et luctus lobortis. Ut ac tortor in velit pulvinar volutpat sit amet sit amet odio. Sed sed lacus aliquam, porta sem eu, commodo ante. Vestibulum elit ipsum, porta a condimentum quis, cursus sit amet mi. Nam vel ante dolor. Mauris sit amet mauris molestie, imperdiet leo in, semper massa. Suspendisse a risus nec risus bibendum dapibus. Ut gravida turpis id pellentesque tincidunt. Aenean non tempor libero, vitae accumsan velit.

Sed egestas ligula sed tellus varius pellentesque. Aenean gravida massa erat, eu volutpat justo auctor eget. Praesent in maximus libero, accumsan vehicula mi. Curabitur at bibendum nisl. Donec vehicula sapien a placerat interdum. Proin quis sollicitudin ex. Nulla massa libero, luctus eget lorem id, fermentum euismod turpis. Nulla nec iaculis augue, eget tincidunt velit. Donec nec turpis a neque lacinia commodo eget ut tortor. Mauris scelerisque, augue vitae sodales consectetur, nisi urna tincidunt nibh, at ultricies mi tortor eget metus. Praesent luctus consectetur nulla quis convallis. Nullam ultricies magna lobortis diam facilisis, ut posuere ex feugiat. Ut sem ipsum, laoreet at varius nec, ullamcorper ut orci.

Integer sit amet mollis dolor, sit amet mattis arcu. Nunc non imperdiet arcu. Quisque tempor vehicula ligula in molestie. Maecenas vel metus in leo condimentum commodo. Duis feugiat velit vitae nisi varius, at efficitur dolor tempor. Nunc purus tortor, maximus sed nisl ac, hendrerit viverra odio. Aliquam erat volutpat. Mauris eu urna tortor. Aenean elementum maximus tortor eu sodales. Etiam nec elit est.

Etiam placerat, mi et laoreet convallis, mi magna lobortis purus, vel blandit mauris nulla in lorem. Vivamus ut nisl id lectus scelerisque suscipit. Integer elit nibh, consequat id massa vehicula, lacinia euismod quam. Ut cursus turpis tempor augue sagittis blandit. Suspendisse ullamcorper risus eu vestibulum commodo. Donec lobortis, velit a lacinia luctus, ipsum dolor tincidunt dui, non porttitor orci sapien id augue. Aliquam nec neque ultricies, congue lorem nec, sagittis velit. Maecenas venenatis vel mauris sit amet facilisis. Cras euismod, lectus vel aliquet posuere, lorem ante bibendum dolor, quis imperdiet velit augue at diam. Duis vitae odio at purus molestie ullamcorper et vitae ante. Nullam eu augue congue, molestie sapien vitae, auctor nisi. Curabitur nec lorem lorem. Nunc ultricies lorem ligula, ut sollicitudin nisi viverra sed. Sed rutrum ante at lectus feugiat, sit amet egestas lectus pretium. Maecenas sollicitudin arcu a risus euismod, sed imperdiet nisi sodales.

Quisque placerat augue tortor, quis ornare elit pellentesque vitae. In rhoncus nulla eget dolor imperdiet, a pellentesque mi euismod. Aenean vel mollis dui. Phasellus at bibendum nulla. Mauris id ex sapien. Sed vitae tincidunt dolor. Etiam facilisis nibh in nisl viverra, eget malesuada lacus aliquet. Curabitur ut lobortis felis. Curabitur vehicula auctor sem ac dictum. In consectetur fringilla orci, at tincidunt velit dignissim consequat.

Nunc nec libero eu nunc dictum aliquam. Donec dolor turpis, aliquet non ligula vel, condimentum porttitor justo. Sed sed ligula at neque pretium semper quis non ligula. Mauris ac varius lectus, in condimentum nulla. Vestibulum magna sem, dignissim et mollis nec, gravida vel leo. Donec blandit imperdiet arcu eu aliquam. Maecenas sit amet pretium elit, sit amet rhoncus lectus. Nam consequat risus a turpis cursus, ut efficitur diam aliquam. Sed eget ligula elementum lorem porta vulputate. Aenean luctus dapibus urna. Suspendisse imperdiet ut felis ut ultricies. Vestibulum efficitur velit eget augue sodales, at maximus eros tincidunt. Aliquam nec tincidunt ante.

Morbi mauris diam, porta eu tempus sed, lobortis quis nulla. Suspendisse mattis eleifend volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae maximus dui, et scelerisque ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi laoreet, velit ac varius varius, risus libero eleifend felis, quis dictum nisi orci a ante. In egestas felis non cursus tincidunt.

Integer vehicula viverra tempor. Integer augue nibh, molestie vel lectus ac, sodales faucibus mauris. Sed maximus ipsum id mauris congue, et interdum quam consectetur. Pellentesque gravida elit mi, sed eleifend orci placerat vitae. Nulla scelerisque purus in erat sodales vehicula. Donec a mauris nunc. Ut sed urna vel massa ornare efficitur.

Quisque enim arcu, luctus id nulla eget, volutpat varius ante. Quisque et pharetra neque. Ut ac odio turpis. Cras porta pulvinar ex id dictum. Vivamus a lacus bibendum, mollis ex ac, convallis neque. Etiam vehicula, velit vitae porttitor vulputate, lectus felis fermentum dolor, a mattis sapien nisi quis risus. Mauris non bibendum velit. Ut vulputate, quam non euismod vestibulum, arcu tortor convallis tellus, sit amet placerat lectus felis eget nulla. Cras nec enim nec libero aliquam mollis tristique nec lorem. Maecenas cursus sit amet lacus nec imperdiet. Sed at neque vel velit pretium aliquam. Curabitur arcu risus, mollis eu eleifend finibus, tempor sollicitudin sem.

Duis eu arcu convallis nisl ornare pulvinar. Cras mattis vulputate nisl at sagittis. Donec at vestibulum augue. Sed placerat enim ut enim rhoncus rutrum. Duis bibendum, nibh ut fermentum eleifend, purus ex bibendum est, sed ornare enim libero id dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse convallis neque sed turpis faucibus elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sodales, neque eget pulvinar vehicula, justo dui bibendum turpis, non euismod ipsum velit quis elit. Nam faucibus ipsum eu ipsum tempor, vitae accumsan arcu placerat. Sed vehicula orci at odio elementum, vel convallis diam fringilla. Fusce mattis varius varius. Fusce arcu felis, interdum eu ex ut, tempus porta massa.

Nulla auctor diam arcu, eget laoreet massa semper eu. Aenean sed arcu lacus. Maecenas dapibus nisi non quam feugiat, nec porta dolor venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras ut tincidunt neque. Curabitur quis consectetur lorem. Maecenas risus lacus, vehicula sed libero vel, porttitor hendrerit massa. Donec vel feugiat sem. Vivamus luctus, tortor et rutrum bibendum, nibh ex semper felis, eu tincidunt sapien mi vitae tortor.

Integer ex risus, iaculis in volutpat mattis, feugiat id urna. Mauris ac metus neque. Cras eu lectus eget erat laoreet dapibus sed nec sem. Integer ut nisl odio. Proin vestibulum nunc sit amet turpis suscipit, in dictum elit laoreet. Sed ipsum quam, ultrices sit amet leo tincidunt, auctor lobortis felis. Ut faucibus accumsan feugiat. Sed at ante vel libero condimentum consectetur. Suspendisse pellentesque hendrerit lectus, id interdum est ultrices vel. Suspendisse vitae mollis est, eget sollicitudin erat. Fusce dui sem, pretium tincidunt quam vitae, sollicitudin volutpat est. Phasellus feugiat leo ac ex semper imperdiet.

Aliquam id nisl vel elit pharetra aliquet ac eu justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce id lectus sed mi vestibulum vestibulum. Donec porta, arcu vitae pharetra porttitor, metus felis consequat purus, sit amet venenatis turpis est in diam. Ut arcu leo, congue id pellentesque vitae, fringilla in mauris. Etiam nisl tellus, sagittis a porta id, elementum eget ex. Praesent vel congue risus, eu lacinia odio. Aenean et ligula lobortis, porttitor metus non, iaculis ante. Sed congue nisl nunc, ac convallis nisi maximus at. Phasellus fringilla feugiat urna congue consectetur. Suspendisse suscipit condimentum ultrices. Phasellus eu lacus dictum, mattis eros eget, convallis orci. Nulla mollis lobortis ligula in mattis.

Vestibulum ipsum metus, fringilla vel velit commodo, rhoncus mattis urna. Sed malesuada, sapien at fermentum gravida, quam mi porttitor urna, malesuada faucibus dui magna non sapien. Nam sodales, leo id dapibus dignissim, felis metus tempor magna, eget semper ante augue non dui. Aliquam nibh massa, dictum et metus sit amet, ullamcorper vestibulum nisl. Maecenas facilisis leo vitae libero feugiat, a facilisis nisi imperdiet. Praesent dolor velit, ultricies vitae lorem at, condimentum ullamcorper dolor. Fusce at mi nibh. Curabitur dui tellus, sollicitudin sed leo nec, elementum malesuada erat. Ut ornare nibh at metus mattis, sed convallis odio volutpat. Proin viverra luctus tortor, in laoreet sapien iaculis sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed efficitur est eu arcu convallis aliquet. Quisque aliquam ligula at velit elementum, ut blandit lacus euismod.

Proin sodales ex et hendrerit malesuada. Aenean fermentum finibus mauris id pulvinar. Sed id elit at ante tempus cursus. Etiam commodo orci non mauris pulvinar, eget luctus odio pharetra. Aenean vitae lectus sed erat porttitor vehicula nec nec nisl. Praesent in pulvinar urna. In porttitor molestie varius. Suspendisse potenti. Aliquam porta rhoncus ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque pellentesque convallis ex at gravida. Morbi id iaculis mauris, eu efficitur urna. Nulla libero arcu, malesuada a lectus porta, consequat vehicula elit. Suspendisse ornare lectus id sem pulvinar, non ornare enim bibendum. Nam sit amet ex odio. Duis venenatis lorem libero, in vestibulum orci vestibulum eu.

Nulla scelerisque rhoncus feugiat. Praesent quis nisi sit amet massa auctor tempor vel maximus nisl. Nunc fermentum scelerisque arcu, vel porttitor nisi accumsan at. Pellentesque fringilla, urna eget euismod auctor, mauris justo vulputate ante, eu vehicula tellus est fringilla urna. Donec eu libero ut nisl lobortis mollis luctus id est. Quisque feugiat libero vitae ipsum eleifend dignissim. Nullam at felis libero. Suspendisse auctor enim vel nisl aliquet, non euismod urna pharetra. Etiam ultricies velit eros, id egestas quam lobortis quis. Proin eget finibus magna. Vivamus porta suscipit accumsan.

Etiam eu ligula at nisl vehicula ullamcorper. Phasellus imperdiet massa velit, quis vulputate urna lacinia id. Cras eu elit ante. Aenean eleifend tellus neque, sed semper nulla pulvinar sed. Proin fringilla dui posuere, interdum nunc nec, iaculis quam. Aenean suscipit at nunc a volutpat. Donec ac quam justo. Curabitur fermentum interdum enim, sit amet posuere sapien ornare ac. Proin felis dui, tincidunt vestibulum blandit nec, ornare a ante. Fusce suscipit mollis justo a accumsan. Mauris cursus risus quam, a mollis libero egestas ac. Duis lobortis semper metus, eu ultrices arcu feugiat sed. Fusce non pulvinar erat, eget aliquet felis. In et nisl tempor, gravida magna eget, consequat erat. 





